"""
Django settings for backend_relab_app project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Загрузка переменных окружения из локального файла .env (если он существует)
env_path = BASE_DIR / '.env'
if env_path.exists():
    with open(env_path, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#') and '=' in line:
                key, val = line.split('=', 1)
                # Удаляем возможные кавычки из значений
                val = val.strip().strip("'").strip('"')
                os.environ[key.strip()] = val



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# TODO (production): вынести в переменные окружения: os.environ.get('DJANGO_SECRET_KEY')
SECRET_KEY = 'django-insecure-(sat5=7b078l6xptlyf&bh_!nm_&x3ywpi5#iv=bc82-r(f!)*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', '10.0.2.2', 'localhost', '127.0.0.1']


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

DJOSER = {
    'USER_CREATE_PASSWORD_RETYPE': False,  # Не требуем re_password
    'SERIALIZERS': {
        'user_create': 'orders.serializers.CustomUserCreateSerializer',
    },
}

# Application definition

INSTALLED_APPS = [
    'daphne',  # ASGI-сервер, должен быть перед django.contrib.staticfiles
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'orders',
    'rest_framework',
    'rest_framework.authtoken',
    'djoser',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'channels',  # Django Channels для WebSocket
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# CORS — актуален только для браузеров, Android-приложение не использует CORS.
# Если будет веб-клиент — настрой CORS_ALLOWED_ORIGINS.
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True


ROOT_URLCONF = 'backend_relab_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend_relab_app.wsgi.application'
ASGI_APPLICATION = 'backend_relab_app.asgi.application'

# Django Channels — слой для WebSocket
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DB_ENGINE = os.getenv('DB_ENGINE', 'mysql').lower()
IS_RECOVERY_MODE = False

if DB_ENGINE == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    import socket
    db_host = os.getenv('DB_HOST', 'localhost')
    db_port = int(os.getenv('DB_PORT', '3306'))
    db_name = os.getenv('DB_NAME', 'relab')
    db_user = os.getenv('DB_USER', 'root')
    db_password = os.getenv('DB_PASSWORD', '30-30-30')

    mysql_available = False
    
    # 1. Быстрая TCP проверка доступности сокета MySQL (таймаут 1.5 сек)
    try:
        s = socket.create_connection((db_host, db_port), timeout=1.5)
        s.close()
        
        # 2. Проверка аутентификации через MySQLdb (mysqlclient) или pymysql
        db_connector = None
        try:
            import MySQLdb
            db_connector = MySQLdb
        except ImportError:
            try:
                import pymysql
                db_connector = pymysql
            except ImportError:
                pass
        
        if db_connector is not None:
            try:
                # В обеих библиотеках поддерживаются универсальные параметры: user, passwd, db
                conn = db_connector.connect(
                    host=db_host,
                    port=db_port,
                    user=db_user,
                    passwd=db_password,
                    db=db_name,
                    connect_timeout=1
                )
                conn.close()
                mysql_available = True
            except Exception as auth_err:
                print(f"[MySQL Auth Error] Authentication failed for {db_user}@{db_host}:{db_port}: {auth_err}")
        else:
            # Если ни одного коннектора для проверки нет, но сокет открыт - разрешаем
            mysql_available = True
    except Exception as conn_err:
        print(f"[MySQL Connection Error] Host {db_host}:{db_port} is unreachable")


    if mysql_available:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.mysql',
                'NAME': db_name,
                'USER': db_user,
                'PASSWORD': db_password,
                'HOST': db_host,
                'PORT': str(db_port),
                'OPTIONS': {
                    'charset': 'utf8mb4',
                    'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                }
            }
        }
    else:
        print("\n!!! [RECOVERY] STARTING IN SQLITE RECOVERY MODE !!!\n")
        IS_RECOVERY_MODE = True
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }






# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ======================
# Настройки компании
# ======================
COMPANY_NAME = 'Relab Service'
COMPANY_DESCRIPTION = 'Локальная CRM система Relab'
