# Generated by Django 5.2 on 2025-04-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=255)),
                ('contact_info', models.CharField(max_length=255)),
                ('additional_info', models.TextField(blank=True)),
                ('telegram_contact', models.CharField(blank=True, max_length=255)),
                ('device_name', models.CharField(max_length=255)),
                ('device_type', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('package_contents', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('description', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('repair', 'Repair'), ('diagnosis', 'Diagnosis')], max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('done', 'Done'), ('pending', 'Pending')], default='new', max_length=50)),
            ],
        ),
    ]
