# Generated by Django 5.2 on 2025-05-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('repair', 'Починкаа'), ('diagnosis', 'Диагностика')], default='repair', max_length=50),
        ),
    ]
