# Generated by Django 5.2 on 2025-05-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('Починка', 'Починка'), ('Диагностика', 'Диагностика')], default='Починка', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('В прогрессе', 'В прогрессе'), ('Готов', 'Готов'), ('Ожидаемый', 'Ожидаемый')], default='Новый', max_length=50),
        ),
    ]
