# Generated by Django 5.2 on 2025-05-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_order_type_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='order',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='orders_photos/'),
        ),
    ]
