# Generated by Django 5.2 on 2025-05-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('repair', 'Починка'), ('diagnosis', 'Диагностика')], default='repair', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В процессе'), ('done', 'Готов'), ('pending', 'Ожидаемый')], default='new', max_length=50),
        ),
    ]
