# Generated by Django 5.2 on 2025-05-13 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_date_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='related_orders', to='orders.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_list', to='orders.order'),
        ),
    ]
