# Generated by Django 5.2 on 2025-05-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_services_alter_service_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='orders', to='orders.service'),
        ),
    ]
