# Generated by Django 5.2 on 2025-05-13 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_service_order_alter_order_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='services',
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='orders.order'),
        ),
    ]
