# Generated by Django 5.2 on 2025-12-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rank',
            field=models.CharField(choices=[('admin', 'Администратор'), ('employee', 'Сотрудник'), ('employee_2', 'Сотрудник 2 ранга')], default='employee', max_length=20, verbose_name='Ранг'),
        ),
    ]
